### ISSUE TITLE
Plase Add Lisence

### ISSUE THREAD

**Issue by pastak** [hitode909/speedline#1]
ここで引用しているのですが、ライセンスが不明で不安なのでライセンスを明記して欲しいです

https://github.com/pastak/Gyazo-Speedline/blob/master/Gyazo/lib/speedline.rb

**Comment by hitode909** [comment]
MIT!!!

https://github.com/hitode909/speedline/commit/0b58da265355ca65c9aa6f1111522a7353154fa3
